name: website

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - .github/workflows/build.yml
      - blog/**
      - docs/**
      - src/**
      - static/**
      - babel.config.js
      - docusaurus.config.js
      - package-lock.json
      - package.json
      - sidebars.js
      - .dockerignore

jobs:
  build_website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/code-tanks/code-tanks-website:latest
          cache-from: type=registry,ref=ghcr.io/code-tanks/code-tanks-website:buildcache
          cache-to: type=registry,ref=ghcr.io/code-tanks/code-tanks-website:buildcache,mode=max
